pepiline {
  agent any
  
  tools {
    nodejs "node"
  }
  parameters {
   string(name: 'container_name', defaultValue:'pagina_web', description: 'Nombre del conteneder')
   string(name: 'image_name', defaultValue:'pagina_img', description: 'Nombre de la imagen docker')
   string(name: 'tag_name', defaultValue:'lts', description: 'Tag de la imagen de la pagina')
   string(name: 'container_port', defaultValue:80, description: 'Puerto para el uso del contenedor')
  }
  
  stages{
    stage('install'){
      steps{
        git branch: 'main', url: 'https://github.com/cadupar20/Taller_Jenkins.git'
        dir ('frontend') {
          sh 'npm install'
        }
      }
    }
  }
  
}
